name: python workflow 

on:
   workflow_dispatch:
   push:

jobs:
    firstjob:
       runs-on: ubuntu-latest
       steps:
       - name: checkout action 
         uses: actions/checkout@v6
         
       - name: setup the python 
         uses: actions/setup-python@v6 

       - name: Installing the requirement
         run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
            
       - name: Run pre-commit hooks
         run: pre-commit run --all-files
         continue-on-error: true

       - name: Run pyright
         run: pyright  

    Dockerpushjob:
       runs-on: ubuntu-latest
       needs: [firstjob]
       steps:
       - name: checkout action 
         uses: actions/checkout@v6

       - name: login to docker hub 
         uses: docker/login-action@v3
         with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 

       - name: Build and push 
         uses: docker/build-push-action@v6
         with:
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/pyapp:v2

    awsecrregistery:
       runs-on: ubuntu-latest
       needs: [ Dockerpushjob ]   
       steps:
       - name: login to AWS 
         uses: aws-actions/configure-aws-credentials@v2
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

       - name: checkout action 
         uses: actions/checkout@v6
         
       - name: login to ECR 
         uses: aws-actions/amazon-ecr-login@v2 
         
       - name: Build, tag, and push docker image to Amazon ECR
         env:
           REGISTRY: 054942703937.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
           REPOSITORY: dev/python
           IMAGE_TAG: ${{ github.sha }}
         run: |
           echo $REGISTRY
           docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG  

